### ISSUE TITLE
Plugin crashes calling Remove Dead Projects if sublime-workspace does not exist

### ISSUE THREAD

**Issue by pkkid** [randy3k/ProjectManager#105]
If using the `Remove Dead Project` action and the sublime-workspace does not exist, the following exception occurs:

```python
Traceback (most recent call last):
  File "/home/pkkid/.config/sublime-text/Packages/ProjectManager/project_manager.py", line 637, in remove_projects_iteratively
    self._remove_project(pname)
  File "/home/pkkid/.config/sublime-text/Packages/ProjectManager/project_manager.py", line 611, in _remove_project
    os.remove(self.project_workspace(project))
FileNotFoundError: [Errno 2] No such file or directory: '/home/pkkid/.config/sublime-text/Packages/User/Projects/foobar.sublime-workspace'
```

**Comment by randy3k** [comment]
Thanks for report, fixed in master.
