### ISSUE TITLE
Exception in thread Thread - The process cannot access the file because it is being used by another process

### ISSUE THREAD

**Issue by evandrocoan** [randy3k/ProjectManager#56]
This just pops on my sublime when I open it:

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "package_control.package_cleanup in D:\User\Documents\SublimeText\Data\Installed Packages\Package Control.sublime-package", line 77, in run
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'D:\\User\\Documents\\SublimeText\\Data\\Installed Packages\\ProjectManager.sublime-package'
```

I am using windows 10 and sublime version 3114.

**Comment by randy3k** [comment]
I guess it is a package control issue.
