### ISSUE TITLE
Do not read if i already have saved multiple projects in ST3 

### ISSUE THREAD

**Issue by zymr-keshav** [randy3k/ProjectManager#72]
# Unable to find any project when already save the project using sublime-text3 and install Project Manager at later stage

I have saved multiple projects in ST3 and it was working fine but I need to remove unnecessary project so installed Project Manager and restart the ST3 in Mac OS Sierra 10.12.6

...

> Any other information you want to share that is relevant to the issue being reported. This might include the lines of code that you have identified as causing the bug, and potential solutions (and your opinions on their merits).

## Expected behaviour
 when click on import folder, it must automatiaccly collect all *.sublime-project file from given main directory ( which we can set somehow)

suppose I have all my projects under `/opt` directory  and we set from the custom setting of Project Manager

{ import_sublime_project_directory: '/opt' }

and when we click on  _import *.sublime-project File_   than it will collect all project and  now we can manage ( rename, remove and other operations)

...

## Actual behavior

when I  am using **Project Manager: Add Project** or  **Project Manager: Open Project** or any other command, from command palette it always pop up the message

**"project list is empty"** and do nothing 

moreover, it also blocks the default keyboard shortcut (`command + control +p`) which display the list of all projects

I have also tried _import *.sublime-project File_ option but it pop-ups 

_"Project file not found"_

so edit settings  **Preferences: Project Manager Settings**

```
{
    "projects_path":["/opt/"],
}
```

and run  _import *.sublime-project File_

but it gives permission error

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 795, in run_
    return self.run(**args)
  File "project_manager in /Users/keshav.m/Library/Application Support/Sublime Text 3/Installed Packages/ProjectManager.sublime-package", line 512, in run
  File "project_manager in /Users/keshav.m/Library/Application Support/Sublime Text 3/Installed Packages/ProjectManager.sublime-package", line 134, in __init__
  File "project_manager in /Users/keshav.m/Library/Application Support/Sublime Text 3/Installed Packages/ProjectManager.sublime-package", line 198, in get_all_projects_info
  File "project_manager in /Users/keshav.m/Library/Application Support/Sublime Text 3/Installed Packages/ProjectManager.sublime-package", line 147, in load_sublime_project_files
PermissionError: [Errno 13] Permission denied: '/opt/proj-ui/application-manager/build/dependency-cache'

```

Why this is checking inside the deeper folder
...

So my question is how to add exiting all project in Project Manager so that I can manage.

## Steps to reproduce

* Install Project Manager and Restart the Sublime text 3
  1. open command palette (`command + shift + p`) and write Project Manager 
  2. click on Add Project, Open Project, Edit Project
  3. nothing happens 

### Environment

```text
ProjectManager:

    version: 0.7.2
    installed via Package Control: True

Sublime Text:

    channel: stable
    version: 3126
    platform: mac
    architecture: x64
```

**Comment by randy3k** [comment]
> when click on import folder, it must automatiaccly collect all *.sublime-project file from given main directory ( which we can set somehow)

I guess you have misunderstood how Project Manager works. You don't have to *import* the folder. In fact, there is no option to import a folder. 
You really don't want to change the setting `projects_path` unless you know what you want to achieve.


> moreover, it also blocks the default keyboard shortcut (command + control +p) which display the list of all projects

 It is expected as Project Manager is a replacement for the built-in manager.

> So my question is how to add exiting all project in Project Manager so that I can manage

Try to follow https://github.com/randy3k/ProjectManager#add-existing-projects-to-project-manager

**Comment by zymr-keshav** [comment]
so according to the link information, I have to move all project's *.sublime-project and *.sublime-workspace files into */Package/User/Projects/* folder. Is that correct?

suppose I have 3 projects under /opt as below and each project has _.sublime-project_ and _.sublime-worspace_ file 
 .
├── projA
├── projB
├── projC

so  I need to cut these files and paste under /User/Packsges/project


but this seems not OK. in future, if I have disabled or remove this package from ST or copy these project from one system to other then before that I have to move back these files to respective project folder.

although I have achieved this by adding each project's path in Package Manager settings but it always takes significant time to load and display the project window, not showing quick as default switch project window.

**Comment by randy3k** [comment]
> if I have disabled or remove this package from ST or copy these project from one system to other then before that I have to move back these files to respective project folder.

You are right

> although I have achieved this by adding each project's path in Package Manager settings but it always takes significant time to load and display the project window, not showing quick as default switch project window.

I suppose you have a lot of others files in the Projects directory. It may take some time as Project Manager has to walk over the directory to search for `*.sublime-project` files. So it is recommended to use move the projects to `/Package/User/Projects/ `.

If you really don't want to move the project files. You may want to use the second option to import existing sublime projects.

**Comment by zymr-keshav** [comment]
So to use Project Manager I have to move my all projects completely from current directory */opt/* to */Package/User/Projects*.

This seems vague. 

agin if I use `import *.sublime-project File` option, it always ends up with pop-ups that "this project is created by Project Manager"  even it is already added. 

Does Package Manager not check whether the project is already added or not?

**Comment by randy3k** [comment]
You cannot import projects which are located in `projects_path`. Those files are supposed to be managed by Project Manager.

**Comment by zymr-keshav** [comment]
not working. I open project folder in sublime and click `import *.sublime-project File`  and it say project file not found.
<img width="1280" alt="keshav_osx 2017-10-28 at 1 29 02 am" src="https://user-images.githubusercontent.com/20237647/32122828-749f0d92-bb7f-11e7-9cb4-e107ebe27ebf.png">

**Comment by randy3k** [comment]
Are you sure that you have opened the sublime project file?

**Comment by zymr-keshav** [comment]
Yes I have opened the respective `.sublime-project` file in the first tab of sublime-text and than select import _*.sublime-project File_  but still same pop-up

**Comment by randy3k** [comment]
I don’t mean opening the file, but to open the project via `subl *.sublime-project`

**Comment by zymr-keshav** [comment]
yes that is working fine
